apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app-deployment-master
  namespace: kubernetes-cluster-aayushgupta01
  labels:
    app: dotnet-app-master
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnet-app-master
  template:
    metadata:
      labels:
        app: dotnet-app-master
    spec:
      containers:
        - name: dotnet-app-master
          image: aayushgup10/nagpdevopsassignment:latest
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-app-master
  namespace: kubernetes-cluster-aayushgupta01
spec:
  type: NodePort
  selector:
    app: dotnet-app-master
  ports:
  - port: 80
    protocol: TCP
    nodePort: 30157
